version: '2'
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /UniVerse_backend && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - celery
    volumes:
      - ${DIRR}/UniVerse_backend:/UniVerse_backend

  

  celery:
    build: .
    container_name: celery
    command: bash -c "cd /UniVerse_backend && celery -A UniVerse_backend worker -l info -P solo"
    volumes:
      - ${DIRR}/UniVerse_backend:/UniVerse_backend

  redis:
    build: .
    container_name: redis
    command: redis-server --bind 0.0.0.0 --protected-mode no
    ports:
      - "6379:6379"